### PR TITLE
#29 Added footer

### PR DESCRIPTION
**Pull request by Sneha123-zudo**
#29 Added footer in the pages that doesn't contain footer. Please review my pull request and suggest changes if something need to be changed.

### CODE REVIEW

**Comment by rko0211** [comment]
Send the link please

**Comment by Sneha123-zudo** [comment]
https://sneha123-zudo.github.io/jgec-previous-year-question-paper/

**Comment by Sneha123-zudo** [comment]
Please check it.

**Comment by Sneha123-zudo** [comment]
Please review it and merged it

**Comment by rko0211** [comment]
Work on updated main branch

**Comment by Sneha123-zudo** [comment]
https://sneha123-zudo.github.io/jgec-previous-year-question-paper/
please check it and merge it

**Comment by rko0211** [comment]
There is an issue check it 
Screen Shot 2024-01-14 at 01 33 35
Footer elements are not aligned in same level

**Comment by Sneha123-zudo** [comment]
Done the changes please check it

**Pull request merged**
