### PR TITLE
Feat/add about page

### LINKED ISSUE #4: Create a Responsive and beautiful About page
Create a beautiful About page and linked it with the navbar . Text content can be of any poem and image must be of Pokemon realated.

### PR DESCRIPTION
**Pull request by AnitSarkar123**
fixes #4 

https://github.com/rko0211/jgec-previous-year-question-paper/assets/135215478/6d6c348a-72c1-485c-8dd7-2a4cc55d192e

### CODE REVIEW

**Comment by rko0211** [comment]
Hey i need to check the responsiveness of the page so please send the link of the demo website .
and send PR in the Test branch , read the Readme.md file

**Comment by AnitSarkar123** [comment]
How to create the link of the website....I don't sent the pr in main branch

**Comment by AnitSarkar123** [comment]
Because if I create it by GitHub pages then the changes don't reflects on it

**Comment by AnitSarkar123** [comment]
> Hey i need to check the responsiveness of the page so please send the link of the demo website .
> and send PR in the Test branch , read the Readme.md file
> 
> 

It is made by bootstrap it is responsive..don't worry about that....after merging in main...you saw this is not responsive then revert that commit

**Comment by AnitSarkar123** [comment]
> Hey i need to check the responsiveness of the page so please send the link of the demo website .
> and send PR in the Test branch , read the Readme.md file
> 
> 

Please check it...and I don't know how to deploy a pr

**Comment by rko0211** [comment]
Open your repository in which changes made then click on setting option
From left sidebar click on pages option 
Then select branch in which u want to deploy
Save 
Wait few minutes you will get the link

**Comment by AnitSarkar123** [comment]
> See this video :
> https://youtu.be/gt2dFv9Vsuc?si=ERUhgDE5IgLiF984

Ok..I will send it tomorrow

**Pull request closed without merging**
