### PR TITLE
Light and dark mode toogle with some changes in css.

### PR DESCRIPTION
**Pull request by Suman599**

### CODE REVIEW

**Comment by rko0211** [comment]
Kindly read the Read the README. md and CONTRIBUTING. md file before open any PR and you are not assigned for this issue. As per the rule of Apertre24 i can not accept your PR at that time.

**Comment by Suman599** [comment]
But I have solved an issue. The issue is to create light and dark mode on the website and also it is mentioned under Apertre.
Screenshot_2024-01-03-15-54-16-160_com android chrome

**Comment by rko0211** [comment]
Iya i know it there but you are not following the guidelines. So kindly read README. md and CONTRIBUTING. md file carefully then again open PR I will merge it if it satisfy all the requirements. Thank you.

**Comment by rko0211** [comment]
First Comment me in issue no #6 i will definitely assign you this task and then open PR.

**Pull request closed without merging**
