### PR TITLE
feat:Addition_Of_about_page

### LINKED ISSUE #4: Create a Responsive and beautiful About page
Create a beautiful About page and linked it with the navbar . Text content can be of any poem and image must be of Pokemon realated.

### PR DESCRIPTION
**Pull request by AnitSarkar123**
fixes #4 
please kindly check it and marge it.

### CODE REVIEW

**Comment by rko0211** [comment]
Kindly read the Readme. Ms file and share demo website link

**Comment by AnitSarkar123** [comment]
Uploading about_JGEC_vid.mp4…

**Comment by AnitSarkar123** [comment]
https://github.com/rko0211/jgec-previous-year-question-paper/assets/135215478/b36f4fd7-3e48-4e44-bfa9-8feb7ad8a669

**Comment by rko0211** [comment]
Hey please don't use card system here just use paragraph and images. Do changes this and send me the website link after that i will merge your PR. and Kindly work on updated branch always. Thank you very much for your contribution.

**Comment by AnitSarkar123** [comment]
> Hey please don't use card system here just use paragraph and images. Do changes this and send me the website link after that i will merge your PR. and Kindly work on updated branch always. Thank you very much for your contribution.
> 

Which you want from me sir....

1.Upwords image and downwards description and name
2. Right side image and left side description and name.
3. Vice-versa of 2.

 I will send PR tomorrow

**Comment by rko0211** [comment]
> > Hey please don't use card system here just use paragraph and images. Do changes this and send me the website link after that i will merge your PR. and Kindly work on updated branch always. Thank you very much for your contribution.
> 
> Which you want from me sir....
> 
> 1.Upwords image and downwards description and name 2. Right side image and left side description and name. 3. Vice-versa of 2.
> 
> I will send PR tomorrow

Iya.. Ok

**Comment by rko0211** [comment]
Kindly send the PR in test branch not in Main branch

**Pull request closed without merging**
