### PR TITLE
issue #52

### PR DESCRIPTION
**Pull request by 123shreyanvi**
jegc
jeg

added get in touch button which opens a form .
added animation on title "JGEC Previous Year Question Paper".
added a button at the bottom scroll to top

### CODE REVIEW

**Comment by rko0211** [comment]
Please send the demo website link.

**Comment by 123shreyanvi** [comment]
> Please send the demo website link.

How to send that do I need to host it

**Comment by 123shreyanvi** [comment]
https://123shreyanvi.github.io/jgec-previous-year-question-paper/ here you go

**Comment by rko0211** [comment]
Hey button is not working, kindly check it

**Comment by 123shreyanvi** [comment]
> Hey button is not working, kindly check it

yes ,I Know  I tried fixing it but couldn't do it 
I don't know where it went wrong .

**Comment by rko0211** [comment]
Listen use this type of code :
HTML:
 <button onclick="topFunction()" id="myBtn" title="Go to top"><i class='fas fa-arrow-circle-up'
            style='font-size:36px'></i></button>

Add some beautiful css in it .

Then add Javascript:


// Get the button
let mybutton = document.getElementById("myBtn");

// When the user scrolls down 20px from the top of the document, show the button
window.onscroll = function () { scrollFunction() };

function scrollFunction() {
  if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
    mybutton.style.display = "block";
  } else {
    mybutton.style.display = "none";
  }
}

// When the user clicks on the button, scroll to the top of the document with smooth effect
function topFunction() {
  window.scrollTo({
    top: 0,
    behavior: "smooth"
  });
}


You can get some idea from it

**Comment by 123shreyanvi** [comment]
> Listen use this type of code : HTML: "button" onclick="topFunction()" id="myBtn" title="Go to top"></button
> 
> Add some beautiful css in it .
> 
> Then add Javascript:
> 
> // Get the button let mybutton = document.getElementById("myBtn");
> 
> // When the user scrolls down 20px from the top of the document, show the button window.onscroll = function () { scrollFunction() };
> 
> function scrollFunction() { if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) { mybutton.style.display = "block"; } else { mybutton.style.display = "none"; } }
> 
> // When the user clicks on the button, scroll to the top of the document with smooth effect function topFunction() { window.scrollTo({ top: 0, behavior: "smooth" }); }
> 
> You can get some idea from it

okay

**Pull request closed without merging**
