### PR TITLE
add hover effect

### PR DESCRIPTION
**Pull request by arghadipmanna101**
- Added hover effect on light and dark button. and made it engaging.

image

- Modify "Click Here" button and it make by beautiful effect.

image

### CODE REVIEW

**Comment by arghadipmanna101** [comment]
PR submitted, check it once.

**Comment by rko0211** [comment]
Please give me website link .

**Comment by arghadipmanna101** [comment]
The website link : 
https://rko0211.github.io/jgec-previous-year-question-paper/

But The PR is not yet merged so you can not see my work in website.

**Comment by rko0211** [comment]
Not my Website bro. Your deployed website. Read the Readme,md file carefully

**Comment by arghadipmanna101** [comment]
> Not my Website bro. Your deployed website. Read the Readme,md file carefully

https://arghadipmanna101.github.io/jgec-previous-year-question-paper/

**Comment by arghadipmanna101** [comment]
check the link once

**Comment by rko0211** [comment]
Nice

**Comment by arghadipmanna101** [comment]
hello, sir i think for this work i deserve medium tag. you can check work.

**Comment by rko0211** [comment]
Ok go Ahead @arghadipmanna101  Make PR before 12AM

**Comment by rko0211** [comment]
You can work on other issue

**Comment by arghadipmanna101** [comment]
what the issue?

**Pull request merged**
