### PR TITLE
#4 Created about page

### PR DESCRIPTION
**Pull request by Sneha123-zudo**
#4 Created a about page and make it responsive and linked it with main page.
https://sneha123-zudo.github.io/jgec-previous-year-question-paper/
please check my PR

### CODE REVIEW

**Comment by rko0211** [comment]
Screen Shot 2024-01-17 at 18 09 50

Page is not responsive and Give a heading of About US and kept the images alternatively right, left, right in this fashion

**Comment by rko0211** [comment]
Navbar is not working in mobile mode

**Comment by Sneha123-zudo** [comment]
How i can the solve the navbar isssue , i tried it but can't able to recognise where is the issue

**Comment by rko0211** [comment]
Add all links from home page for navbar, Including all the JavaScript file link then try this

**Comment by Sneha123-zudo** [comment]
Now check i done the changes

**Comment by rko0211** [comment]
Screen Shot 2024-01-17 at 23 40 25

Still issue little bit give some margin top and listen work on Updated Main branch

**Comment by Sneha123-zudo** [comment]
Done

**Comment by Sneha123-zudo** [comment]
Please check it....i already added the about page link all pages

**Comment by Sneha123-zudo** [comment]
please merge it as i done the all changes

**Comment by rko0211** [comment]
It can be better, Ok

**Pull request merged**
