### PR TITLE
Added light and dark mode toggle

### PR DESCRIPTION
**Pull request by Suman599**
Light mode dark mode toggle added to the website.

### CODE REVIEW

**Comment by rko0211** [comment]
Hey please send the link also

**Comment by Suman599** [comment]
> Hey please send the link also

https://suman599.github.io/light-and-dark-mode/

**Comment by Suman599** [comment]
> Hey please send the complete PR on updated main branch as you have done earlier not just heading.

Ya i have sent the PR in updated main branch itself.

**Comment by Suman599** [comment]
> Hey please send the complete PR on updated main branch as you have done earlier not just heading.

Ok check I have sent the complete PR in the updated main branch

**Pull request merged**
