### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by arghadipmanna101**
Update :
1. Add contributors name.
2. Add some gif.
3. Update how to contribute in the project.

### CODE REVIEW

**Comment by rko0211** [comment]
Give the screenshot

**Comment by arghadipmanna101** [comment]
Which screenshot?

**Comment by rko0211** [comment]
> Which screenshot?

Readme.md

**Comment by arghadipmanna101** [comment]
- Added how to contribute.
WhatsApp Image 2024-01-17 at 19 06 28_b3796992

- Added contributors name and add some gif.
WhatsApp Image 2024-01-17 at 19 06 28_a3f82a22

**Comment by arghadipmanna101** [comment]
I have given the PR. You can check my Repositories as demo.

**Comment by rko0211** [comment]
Ok nice

**Comment by arghadipmanna101** [comment]
Thank you..

**Pull request merged**
