### PR TITLE
added the css changes

### PR DESCRIPTION
**Pull request by deepbeatz**

### CODE REVIEW

**Comment by rko0211** [comment]
kindly share website link you deploy in github

**Comment by rko0211** [comment]
What is the update @deepbeatz

**Comment by deepbeatz** [comment]
I have given the pr request, do I need to do anything else?

**Comment by rko0211** [comment]
kindly share website link you deploy in github. Have you seen this message ?

**Comment by deepbeatz** [comment]
i have already given the pr as u can see @rko0211 , what else do i need to do?

**Comment by rko0211** [comment]
> i have already given the pr as u can see @rko0211 , what else do i need to do?

Kindly share the website link . Read the README. Md file carefully

**Comment by deepbeatz** [comment]
https://deepbeatz.github.io/jgec-previous-year-question-paper/     
link to deployed branch

**Comment by rko0211** [comment]
Hey can you make the buttons better because i have seen that you  have  change the Background color and add a transition in the button, It can be better i think. Thank you.

**Comment by deepbeatz** [comment]
the button color was blue before which was looking bad and so i changed it to the official colour of the website and changes a bit of the hover animation.

**Comment by rko0211** [comment]
> the button color was blue before which was looking bad and so i changed it to the official colour of the website and changes a bit of the hover animation.

First of all this color is not official color of the website , and second it can be better ..

**Comment by rko0211** [comment]
What is your update @deepbeatz

**Pull request closed without merging**
