### PR TITLE
Added Dark mode and light mode toogle and changed some css.

### PR DESCRIPTION
**Pull request by Suman599**

### CODE REVIEW

**Comment by rko0211** [comment]
Kindly share the Demo website link.(host on github)

**Comment by Suman599** [comment]
> Kindly share the Demo website link.(host on github)

Here is the demo website link- https://suman599.github.io/light-and-dark-mode/

**Comment by rko0211** [comment]
Nice can you design the **change mode** button  in better way after that i will merge your PR.

**Comment by rko0211** [comment]
And resolve the issue in the marque tag before footer that is not visible in Dark mode .

**Pull request closed without merging**
