### PR TITLE
Added light and dark mode toggle along with some changes in CSS.

### PR DESCRIPTION
**Pull request by Suman599**

### CODE REVIEW

**Comment by Suman599** [comment]
https://github.com/Suman599/light-and-dark-mode

**Comment by rko0211** [comment]
Kindly design **Change mode** button

**Comment by rko0211** [comment]
And kindly share the demo website link in this comment section

**Comment by Suman599** [comment]
> Kindly design **Change mode** button

I have done that - https://suman599.github.io/light-and-dark-mode/

**Comment by rko0211** [comment]
Sorry to say your changes affect the Footer part also. So kindly keep footer as it is and work on only dark and light mode features. Design of Change mode button can be better ..

**Comment by Suman599** [comment]
> Sorry to say your changes affect the Footer part also. So kindly keep footer as it is and work on only dark and light mode features. Design of Change mode button can be better ..

I have not done anything with the footer part. and i can't see any major differences with the original webpage. I have just changed some text color because they are not visible in the dark mode.

**Pull request closed without merging**
